sudo: required
services:
  - docker

before_install:
  - docker build -t sazzadk/docker-app -f Dockerfile.dev .

script:
  - docker run sazzadk/docker-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-823662392856"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
